"""debug_preflight: readiness audit (todo T7).

Every check reports PASS/FAIL + evidence + fix command. Root and env inject
so tests never depend on this machine. Read-only: two runs on an idle tree
are byte-identical (no timestamps in output).
"""
import json
import os

from tools import debug_preflight as preflight


def _env(**overrides):
    env = {"PATH": "x"}
    env.update(overrides)
    return env


def test_empty_tree_fails_game_dir_naming_the_var(tmp_path):
    out = preflight.audit(root=str(tmp_path), env=_env())
    by_name = {c["check"]: c for c in out["checks"]}
    assert by_name["game-dir"]["verdict"] == "FAIL"
    assert "FUSIONRPG_GAME_DIR" in by_name["game-dir"]["fix"]
    # Dependents fail (never crash, never SKIP-silence) naming the same cause.
    assert by_name["interop-refs"]["verdict"] == "FAIL"
    assert by_name["dll-freshness"]["verdict"] == "FAIL"


def test_full_tree_passes(tmp_path):
    game = tmp_path / "game"
    (game / "BepInEx" / "core").mkdir(parents=True)
    (game / "BepInEx" / "interop").mkdir(parents=True)
    (game / "PlantsVsZombiesRH.exe").write_text("x")
    (tmp_path / "dist" / "FusionRpg.Server" / "data").mkdir(parents=True)
    (tmp_path / "dist" / "FusionRpg.Server" / "data" / "rpg-hot.sqlite").write_text("x")
    (tmp_path / "dist" / "FusionRpg.Server" / "FusionRpg.Core.dll").write_text("x")
    # The frontend is its own SIBLING repository, which is the layout that actually exists - `web/`
    # is absent from every commit on every ref, so a fixture planting it below `tmp_path` described a
    # tree this repository has never had, and the check that read it was false-failing for real. The
    # property this test guards is unchanged: a COMPLETE tree reports no failing check. Only the
    # fixture is corrected, and only because its premise was false rather than its assertion.
    ws = tmp_path / "workspace"
    root = ws / "gk-fusion"
    root.mkdir(parents=True)
    (ws / "gk-core").mkdir()
    (ws / "gk-data").mkdir()
    (ws / "gk-web" / "web" / "fusion-rpg-web" / "node_modules").mkdir(parents=True)
    # dist/ belongs to the ROOT being audited, which is now the sibling repository, not tmp_path.
    (root / "dist" / "FusionRpg.Server" / "data").mkdir(parents=True)
    (root / "dist" / "FusionRpg.Server" / "data" / "rpg-hot.sqlite").write_text("x")
    (root / "dist" / "FusionRpg.Server" / "FusionRpg.Core.dll").write_text("x")
    env = _env(FUSIONRPG_GAME_DIR=str(game))
    out = preflight.audit(root=str(root), env=env)
    failing = [c["check"] for c in out["checks"]
               if c["verdict"] == "FAIL" and c["check"] != "server-port"]
    assert failing == [], failing
    assert all(set(c) >= {"check", "verdict", "evidence", "fix"}
               for c in out["checks"])


def test_dll_freshness_ignores_build_output_under_obj(tmp_path):
    """Real false-FAIL found live 2026-09-20: ``obj/**/*.cs`` is regenerated by every local build
    with a fresh mtime, which made a genuinely newer published DLL read as stale. Build output is
    never source, so it must not count toward the freshness comparison."""
    src = tmp_path / "src" / "FusionRpg.Core"
    src.mkdir(parents=True)
    real = src / "Real.cs"
    real.write_text("x")
    obj = src / "obj" / "Debug" / "net6.0"
    obj.mkdir(parents=True)
    generated = obj / "FusionRpg.Core.AssemblyInfo.cs"
    generated.write_text("x")
    dll = tmp_path / "dist" / "FusionRpg.Server" / "FusionRpg.Core.dll"
    dll.parent.mkdir(parents=True)
    dll.write_text("x")
    os.utime(real, (1000, 1000))
    os.utime(generated, (3000, 3000))
    os.utime(dll, (2000, 2000))

    result = preflight._dll_freshness(str(tmp_path), _env(), str(tmp_path / "game"))
    assert result["verdict"] == "PASS", result


def test_dll_freshness_still_fails_when_real_source_is_newer(tmp_path):
    """The companion half: a genuinely newer SOURCE file still fails the check."""
    src = tmp_path / "src" / "FusionRpg.Core"
    src.mkdir(parents=True)
    real = src / "Real.cs"
    real.write_text("x")
    dll = tmp_path / "dist" / "FusionRpg.Server" / "FusionRpg.Core.dll"
    dll.parent.mkdir(parents=True)
    dll.write_text("x")
    os.utime(real, (3000, 3000))
    os.utime(dll, (2000, 2000))

    result = preflight._dll_freshness(str(tmp_path), _env(), str(tmp_path / "game"))
    assert result["verdict"] == "FAIL", result


def test_audit_is_deterministic(tmp_path):
    first = preflight.audit(root=str(tmp_path), env=_env())
    second = preflight.audit(root=str(tmp_path), env=_env())
    assert json.dumps(first, sort_keys=True) == json.dumps(second, sort_keys=True)


# --- node_modules resolution -------------------------------------------------------------------
# The frontend lives in its own repository. This check used to look only at
# `<root>/web/fusion-rpg-web`, a layout this repository has never had (`web/` is absent from every
# commit on every ref), so it reported a false FAIL from a standalone clone. It now asks
# `keepverse_roots.web_root` - the one root contract, four implementations, already drifted twice.
#
# Fixtures reproduce the layout that contract actually detects: `_layout` calls a directory a
# workspace when it holds BOTH `gk-core` and `gk-data`, and a sibling web repository is then found by
# name. A bespoke resolver that globbed the parent would not resolve these fixtures at all, which is
# the point - the tests are written against the contract, not against one implementation of it.


def _workspace(tmp_path, *, web=True, web_node_modules=True):
    """A workspace whose gk-fusion is the caller's root. Returns (root, workspace)."""
    ws = tmp_path / "workspace"
    root = ws / "gk-fusion"
    root.mkdir(parents=True)
    (ws / "gk-core").mkdir()
    (ws / "gk-data").mkdir()
    if web:
        app = ws / "gk-web" / "web" / "fusion-rpg-web"
        app.mkdir(parents=True)
        if web_node_modules:
            (app / "node_modules").mkdir()
    return root, ws


def test_node_modules_resolves_through_the_canonical_sibling(tmp_path):
    root, ws = _workspace(tmp_path)
    result = preflight._node_modules(str(root), {})
    assert result["verdict"] == "PASS", result
    # The evidence must be the path the BUILD uses, not merely something that exists.
    assert result["evidence"] == str(ws / "gk-web" / "web" / "fusion-rpg-web" / "node_modules"), result


def test_node_modules_the_override_wins_over_a_discovered_sibling(tmp_path):
    """Pins PRECEDENCE. The override is the only place node_modules exists, so a resolver that
    consulted the discovered sibling first - or ignored the override - could not pass."""
    root, ws = _workspace(tmp_path, web_node_modules=False)
    elsewhere = tmp_path / "elsewhere"
    (elsewhere / "web" / "fusion-rpg-web" / "node_modules").mkdir(parents=True)
    result = preflight._node_modules(
        str(root), {"KEEPVERSE_WEB_ROOT": str(elsewhere)})
    assert result["verdict"] == "PASS", result
    assert result["evidence"].startswith(str(elsewhere)), result


def test_an_override_naming_a_missing_directory_is_refused_not_ignored(tmp_path):
    """Pins VALIDATION, and it is the shape the audit called out: the sibling HAS node_modules, so
    silently ignoring a broken override would produce a confident PASS about the wrong tree."""
    root, ws = _workspace(tmp_path)  # sibling present and complete
    result = preflight._node_modules(
        str(root), {"KEEPVERSE_WEB_ROOT": str(tmp_path / "not-a-directory")})
    assert result["verdict"] == "FAIL", result
    assert "KEEPVERSE_WEB_ROOT" in result["evidence"], result


def test_an_absent_gk_web_refuses_naming_the_repository(tmp_path):
    root, ws = _workspace(tmp_path, web=False)
    result = preflight._node_modules(str(root), {})
    assert result["verdict"] == "FAIL", result
    assert "gk-web" in result["evidence"], result
    assert "KEEPVERSE_WEB_ROOT" in result["fix"], result


def test_a_present_web_repo_without_installed_packages_still_fails(tmp_path):
    """The check is about node_modules, not about the repository existing."""
    root, ws = _workspace(tmp_path, web_node_modules=False)
    result = preflight._node_modules(str(root), {})
    assert result["verdict"] == "FAIL", result
    assert "node_modules" in result["evidence"], result
