"""debug_preflight: readiness audit (todo T7).

Every check reports PASS/FAIL + evidence + fix command. Root and env inject
so tests never depend on this machine. Read-only: two runs on an idle tree
are byte-identical (no timestamps in output).
"""
import json
import os

from tools import debug_preflight as preflight


def _env(**overrides):
    env = {"PATH": "x"}
    env.update(overrides)
    return env


def test_empty_tree_fails_game_dir_naming_the_var(tmp_path):
    out = preflight.audit(root=str(tmp_path), env=_env())
    by_name = {c["check"]: c for c in out["checks"]}
    assert by_name["game-dir"]["verdict"] == "FAIL"
    assert "FUSIONRPG_GAME_DIR" in by_name["game-dir"]["fix"]
    # Dependents fail (never crash, never SKIP-silence) naming the same cause.
    assert by_name["interop-refs"]["verdict"] == "FAIL"
    assert by_name["dll-freshness"]["verdict"] == "FAIL"


def test_full_tree_passes(tmp_path):
    game = tmp_path / "game"
    (game / "BepInEx" / "core").mkdir(parents=True)
    (game / "BepInEx" / "interop").mkdir(parents=True)
    (game / "PlantsVsZombiesRH.exe").write_text("x")
    (tmp_path / "dist" / "FusionRpg.Server" / "data").mkdir(parents=True)
    (tmp_path / "dist" / "FusionRpg.Server" / "data" / "rpg-hot.sqlite").write_text("x")
    (tmp_path / "dist" / "FusionRpg.Server" / "FusionRpg.Core.dll").write_text("x")
    (tmp_path / "web" / "fusion-rpg-web" / "node_modules").mkdir(parents=True)
    env = _env(FUSIONRPG_GAME_DIR=str(game))
    out = preflight.audit(root=str(tmp_path), env=env)
    failing = [c["check"] for c in out["checks"]
               if c["verdict"] == "FAIL" and c["check"] != "server-port"]
    assert failing == [], failing
    assert all(set(c) >= {"check", "verdict", "evidence", "fix"}
               for c in out["checks"])


def test_dll_freshness_ignores_build_output_under_obj(tmp_path):
    """Real false-FAIL found live 2026-09-20: ``obj/**/*.cs`` is regenerated by every local build
    with a fresh mtime, which made a genuinely newer published DLL read as stale. Build output is
    never source, so it must not count toward the freshness comparison."""
    src = tmp_path / "src" / "FusionRpg.Core"
    src.mkdir(parents=True)
    real = src / "Real.cs"
    real.write_text("x")
    obj = src / "obj" / "Debug" / "net6.0"
    obj.mkdir(parents=True)
    generated = obj / "FusionRpg.Core.AssemblyInfo.cs"
    generated.write_text("x")
    dll = tmp_path / "dist" / "FusionRpg.Server" / "FusionRpg.Core.dll"
    dll.parent.mkdir(parents=True)
    dll.write_text("x")
    os.utime(real, (1000, 1000))
    os.utime(generated, (3000, 3000))
    os.utime(dll, (2000, 2000))

    result = preflight._dll_freshness(str(tmp_path), _env(), str(tmp_path / "game"))
    assert result["verdict"] == "PASS", result


def test_dll_freshness_still_fails_when_real_source_is_newer(tmp_path):
    """The companion half: a genuinely newer SOURCE file still fails the check."""
    src = tmp_path / "src" / "FusionRpg.Core"
    src.mkdir(parents=True)
    real = src / "Real.cs"
    real.write_text("x")
    dll = tmp_path / "dist" / "FusionRpg.Server" / "FusionRpg.Core.dll"
    dll.parent.mkdir(parents=True)
    dll.write_text("x")
    os.utime(real, (3000, 3000))
    os.utime(dll, (2000, 2000))

    result = preflight._dll_freshness(str(tmp_path), _env(), str(tmp_path / "game"))
    assert result["verdict"] == "FAIL", result


def test_audit_is_deterministic(tmp_path):
    first = preflight.audit(root=str(tmp_path), env=_env())
    second = preflight.audit(root=str(tmp_path), env=_env())
    assert json.dumps(first, sort_keys=True) == json.dumps(second, sort_keys=True)


# --- node_modules resolution -------------------------------------------------------------------
# The check used to look only at <root>/web/fusion-rpg-web. The frontend now lives in its own
# repository one level up, so from a standalone clone of THIS repository that path never resolves
# and the preflight reports a false FAIL. Measured live 2026-10-03 against
# <workspace>/gk-fusion/tools/debug-mcp: node-modules FAIL while the real web app had
# node_modules present at <workspace>/gk-web/web/fusion-rpg-web.
#
# Every test below roots its tree at <tmp>/<sibling-parent>/<repo> so the sibling scan can only
# ever see directories this test created. Using tmp_path directly would let any other test's
# leftovers in pytest's tmp base satisfy the scan, which is a false PASS, not a hermetic failure.


def _workspace(tmp_path, repo="gk-fusion", sibling=None):
    """Build an isolated <parent>/<repo> (+ optional sibling repo) and return (repo_root, parent)."""
    parent = tmp_path / "workspace"
    root = parent / repo
    root.mkdir(parents=True)
    if sibling:
        (parent / sibling / "web" / "fusion-rpg-web" / "node_modules").mkdir(parents=True)
    return root, parent


def test_node_modules_found_in_the_sibling_repository(tmp_path):
    """The regression this fixes: the frontend in its own repository, resolved without config."""
    root, _ = _workspace(tmp_path, sibling="gk-web")
    result = preflight._node_modules(str(root), _env())
    assert result["verdict"] == "PASS", result
    assert "gk-web" in result["evidence"], result


def test_node_modules_still_found_when_vendored_under_root(tmp_path):
    """The pre-split layout keeps working - this is additive, not a replacement."""
    root, _ = _workspace(tmp_path)
    (root / "web" / "fusion-rpg-web" / "node_modules").mkdir(parents=True)
    result = preflight._node_modules(str(root), _env())
    assert result["verdict"] == "PASS", result
    assert "vendored" in result["evidence"], result


def test_node_modules_env_var_is_configuration_and_wins(tmp_path):
    root, _ = _workspace(tmp_path)
    elsewhere = tmp_path / "elsewhere" / "app"
    (elsewhere / "node_modules").mkdir(parents=True)
    result = preflight._node_modules(str(root), _env(FUSIONRPG_WEB_ROOT=str(elsewhere)))
    assert result["verdict"] == "PASS", result
    assert "FUSIONRPG_WEB_ROOT" in result["evidence"], result


def test_node_modules_absent_everywhere_fails_naming_the_env_var(tmp_path):
    """The negative half: a genuine miss still FAILs, and the fix names the configuration to set."""
    root, _ = _workspace(tmp_path)  # no sibling, no vendored copy, no env var
    result = preflight._node_modules(str(root), _env())
    assert result["verdict"] == "FAIL", result
    assert "FUSIONRPG_WEB_ROOT" in result["fix"], result
    assert result["fix"].startswith("set $env:FUSIONRPG_WEB_ROOT"), result


def test_server_port_branches():
    up = preflight._port_state(probe=lambda: (False, True))
    assert up["verdict"] == "PASS"
    free = preflight._port_state(probe=lambda: (True, False))
    assert free["verdict"] == "PASS"
    stale = preflight._port_state(probe=lambda: (False, False))
    assert stale["verdict"] == "FAIL"
    assert "5088" in stale["fix"]


def test_server_registers_debug_preflight():
    import asyncio
    from server import mcp
    tools = asyncio.run(mcp.list_tools())
    assert "debug_preflight" in [t.name for t in tools]


def test_live_state_separates_injector_connection_from_idle_board():
    snapshots = []

    def request(method, path, params=None):
        if path == "/health":
            return {"status": 200, "body": {"ok": True, "injectorConnected": True,
                                              "lastHeartbeatUtc": "2026-09-14T00:00:00+00:00",
                                              "source": "injector", "simEnabled": False}}
        if path == "/api/debug/session":
            return {"status": 200, "body": {"sessionActive": False}}
        if path == "/api/debug/snapshot":
            snapshots.append(True)
            return {"status": 200, "body": {"ok": True}}
        if not snapshots and params["afterId"] < 9:
            return {"status": 200, "body": {"items": [{"id": 9}]}}
        if snapshots and params["afterId"] == 9:
            return {"status": 200, "body": {"items": [{"id": 10, "kind": "debug.snapshot",
                "matchKey": None, "payload": {"match": {"phase": "Idle"}}}]}}
        return {"status": 200, "body": {"items": []}}

    out = preflight.live_state(request=request, process_probe=lambda: True)
    assert snapshots == [True]
    assert out["injector"]["connected"] is True
    assert out["board"]["observed"] is True
    assert out["board"]["state"] == "idle"
    assert out["ready"] is False
    assert "injector liveness alone" in out["fix"]


def test_live_state_requires_a_fresh_snapshot_for_ready():
    def request(method, path, params=None):
        if path == "/health":
            return {"status": 200, "body": {"ok": True, "injectorConnected": True}}
        if path in ("/api/debug/session", "/api/debug/snapshot"):
            return {"status": 200, "body": {"ok": True}}
        return {"status": 200, "body": {"items": []}}

    now = iter((0, 6))
    out = preflight.live_state(request=request, process_probe=lambda: True,
                               monotonic=lambda: next(now), sleep=lambda _: None)
    assert out["injector"]["connected"] is True
    assert out["board"]["observed"] is False
    assert out["ready"] is False
    assert "did not emit debug.snapshot" in out["fix"]


def test_board_state_only_calls_non_idle_observation_live():
    assert preflight._board_state({"payload": {"match": {"phase": "Idle"}}})[0] == "idle"
    assert preflight._board_state({"payload": {"match": {"phase": "Loading"}}})[0] == "loading"
    assert preflight._board_state({"payload": {"match": {"phase": "InMatch"}}})[0] == "active"


def _live_state_request_with_snapshot(phase, game_state_body=None):
    """Mirrors test_live_state_separates_injector_connection_from_idle_board's own stub shape
    (the `snapshots` gate is what makes _event_max_id's watermark search converge before the
    actual debug.snapshot poll begins) -- only adds a POST /api/debug/game-state branch."""
    snapshots = []

    def request(method, path, params=None):
        if path == "/health":
            return {"status": 200, "body": {"ok": True, "injectorConnected": True}}
        if path == "/api/debug/session":
            return {"status": 200, "body": {"ok": True}}
        if method == "POST" and path == "/api/debug/game-state":
            if game_state_body is None:
                return {"status": 404, "body": {"raw": "not found"}}
            return {"status": 200, "body": game_state_body}
        if path == "/api/debug/snapshot":
            snapshots.append(True)
            return {"status": 200, "body": {"ok": True}}
        if not snapshots and (params or {}).get("afterId", 999) < 9:
            return {"status": 200, "body": {"items": [{"id": 9}]}}
        if snapshots and (params or {}).get("afterId") == 9:
            return {"status": 200, "body": {"items": [{"id": 10, "kind": "debug.snapshot",
                "matchKey": None, "payload": {"match": {"phase": phase}}}]}}
        return {"status": 200, "body": {"items": []}}
    return request


def test_game_state_cross_check_unavailable_falls_back_to_snapshot():
    """Route missing (e.g. not yet merged into this checkout) -- unchanged legacy behavior."""
    out = preflight.live_state(request=_live_state_request_with_snapshot("InMatch"),
                               process_probe=lambda: True)
    assert out["ready"] is True
    assert "gameStateCrossCheck" not in out["board"]


def test_game_state_cross_check_agrees_leaves_ready_unchanged():
    body = {"ok": True, "live": {"ok": True, "matchPhase": "InMatch", "phaseMismatch": False,
                                  "plantCount": 1, "zombieCount": 1, "liveState": "InMatch"}}
    out = preflight.live_state(request=_live_state_request_with_snapshot("InMatch", body),
                               process_probe=lambda: True)
    assert out["ready"] is True
    assert out["board"]["gameStateCrossCheck"]["liveState"] == "InMatch"


def test_game_state_cross_check_overrides_stale_snapshot_phase():
    """Real 2026-09-14 incident: matchPhase said InMatch during a genuine defeat with 0 real
    entities. The real counts must win, and the fix message must say so."""
    body = {"ok": True, "live": {"ok": True, "matchPhase": "InMatch", "phaseMismatch": True,
                                  "plantCount": 0, "zombieCount": 0,
                                  "liveState": "MatchEndedBoardStillAlive"}}
    out = preflight.live_state(request=_live_state_request_with_snapshot("InMatch", body),
                               process_probe=lambda: True)
    assert out["ready"] is False
    assert out["board"]["state"] == "active"  # snapshot's own reading, left as-is for reference
    assert "real Unity object counts" in out["fix"]
    assert "MatchEndedBoardStillAlive" in out["fix"]
